[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nodejs_18', 'nodejs', 'npm]

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader',
    'composer install --optimize-autoloader --no-dev',
    'npm ci'
]

[phases.build]
cmds = [
    'npm run build',
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache',
    'composer install --no-dev --optimize-autoloader',
    'npm ci',
    'npm run build',
    'chmod -R 775 storage',
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'