[providers]
php = "8.2"

[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nodejs_18', 'python3']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader',
    'npm ci'
]

[phases.build]
cmds = [
    'npm run build',
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'